options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image'
    script: |
        #!/bin/bash
        # Fetch the latest tags from the remote
        git fetch --tags

        # Get the latest tag from the master branch
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null)

        # Check if a tag exists
        if [ -z "$latest_tag" ]; then
            new_tag="0.0.0"
        else
            # Split the latest tag into its components (assuming semantic versioning)
            IFS='.' read -r -a version_parts <<< "$latest_tag"
        fi

        # Get the commit message for the current commit
        COMMIT_MESSAGE=$(git log -1 --pretty=%B $COMMIT_SHA)

        # Determine the version increment based on the commit message prefix
        if [[ $COMMIT_MESSAGE == release:* ]]; then
            version_parts[0]=$((version_parts[0] + 1))
            version_parts[1]=0
            version_parts[2]=0
        elif [[ $COMMIT_MESSAGE == feat:* ]]; then
            version_parts[1]=$((version_parts[1] + 1))
            version_parts[2]=0
        elif [[ $COMMIT_MESSAGE == fix:* ]]; then
            version_parts[2]=$((version_parts[2] + 1))
        else
            echo "Commit message does not match any known prefix. Exiting."
            exit 0
        fi

        # Construct the new tag
        new_tag="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"

        echo "Updated tag to $new_tag and pushed to remote."

        # Export the new tag as an environment variable
        echo $new_tag > /workspace/new_tag.env
        
        # verifying cat
        cat /workspace/new_tag.env
  

  - name: 'docker'
    entrypoint: sh
    args: ["-c", "docker build -t europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/ds-usecase-image:$(cat /workspace/new_tag.env) ."]

  - name: "docker"
    entrypoint: sh
    args: ["-c", "docker push europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/ds-usecase-image:$(cat /workspace/new_tag.env)"]
  
  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    script: |
        #!/bin/bash

        new_tag=$(cat /workspace/new_tag.env)
        
        # Create a new tag
        git tag $new_tag

        # Push the new tag to the remote repository
        git push origin $new_tag

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["gcloud", "auth", "configure-docker", "europe-west2-docker.pkg.dev"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["gcloud", "container", "clusters", "get-credentials", "cluster-1", "--region=europe-west2", "--project=playpen-ff1b21"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["kubectl", "config", "current-context"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    script: |
      gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://europe-west2-docker.pkg.dev

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    env:
      - 'new_tag=$(cat /workspace/new_tag.env)'
    args: ["helm", "upgrade", "--install", "ds-usecase-temp", "--set=image.repository=europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/ds-usecase-image", "--set=image.tag=$new_tag", "oci://europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/service-with-auth", "--version", "0.1.0"]
