options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image'
    secretEnv: ['GIT_PAT']
    script: |
        #!/bin/bash

        # # Fetch the latest tags from the remote
        # git fetch --tags

        # # Get the latest tag from the master branch
        # latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null)

        # # Check if a tag exists
        # if [ -z "$latest_tag" ]; then
        #     new_tag="0.0.0"
        # else
        #     # Split the latest tag into its components (assuming semantic versioning)
        #     IFS='.' read -r -a version_parts <<< "$latest_tag"
        # fi

        # # Get the commit message for the current commit
        # COMMIT_MESSAGE=$(git log -1 --pretty=%B $COMMIT_SHA)

        # # Determine the version increment based on the commit message prefix
        # if [[ $COMMIT_MESSAGE == release:* ]]; then
        #     version_parts[0]=$((version_parts[0] + 1))
        #     version_parts[1]=0
        #     version_parts[2]=0
        # elif [[ $COMMIT_MESSAGE == feat:* ]]; then
        #     version_parts[1]=$((version_parts[1] + 1))
        #     version_parts[2]=0
        # elif [[ $COMMIT_MESSAGE == fix:* ]]; then
        #     version_parts[2]=$((version_parts[2] + 1))
        # else
        #     echo "Commit message does not match any known prefix. Exiting."
        #     exit 0
        # fi

        # # Construct the new tag
        # new_tag="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"

        # # Set the remote URI to push the new tag
        # git remote set-url origin https://vishwaksenan:$GIT_PAT@github.com/vishwaksenan/poc-gcp-cloud-build.git
        
        # # Set the tag 
        # git tag $new_tag

        # # Push the new tag to the remote repository
        # git push origin $new_tag

        # # Saving tag in a env file so that it can be used in other steps
        # echo $new_tag > /workspace/new_tag.env

        # echo "Updated tag to $new_tag and pushed to remote. Saved the new tag $new_tag in file /workspace/new_tag.env"

        echo "$(tr -dc 'a-z' < /dev/urandom | head -c 1)$(tr -dc 'a-z0-9' < /dev/urandom | head -c 9)" > /workspace/rand
        echo "--------- Random String ---------"
        cat /workspace/rand
  

  - name: 'docker'
    entrypoint: sh
    args: ["-c", "docker build -t europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/ds-usecase-image-$(cat /workspace/rand):test-$(cat /workspace/rand) ."]

  - name: "docker"
    entrypoint: sh
    args: ["-c", "docker push europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/ds-usecase-image-$(cat /workspace/rand):test-$(cat /workspace/rand)"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["gcloud", "auth", "configure-docker", "europe-west2-docker.pkg.dev"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["gcloud", "container", "clusters", "get-credentials", "cluster-1", "--region=europe-west2", "--project=playpen-ff1b21"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["kubectl", "config", "current-context"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    script: |
      gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://europe-west2-docker.pkg.dev

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    script: |
      #!/bin/bash
      rid=$(cat /workspace/rand)
      helm upgrade --install ds-usecase-temp-$rid --set=image.repository=europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/ds-usecase-image-$rid --set=image.tag=test-$rid --set=rid=$rid oci://europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/service-with-auth --version 0.1.0
      
  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["sleep", "180"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    script: |
      #!/bin/bash
      rid=$(cat /workspace/rand)
      helm uninstall ds-usecase-temp-$rid
  
  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    entrypoint: sh
    args: ["-c", "gcloud artifact docker images delete europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/ds-usecase-image-$(cat /workspace/rand)"]
      
availableSecrets:
  secretManager:
  - versionName: projects/playpen-ff1b21/secrets/personal-git-connection-github-oauthtoken-4b3be7/versions/2
    env: 'GIT_PAT'
