options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image'
    script: |
        #!/bin/bash
        
        # Fetch the latest tags from the remote
        git fetch --tags

        # Get the latest tag from the master branch
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null)

        # Check if a tag exists
        if [ -z "$latest_tag" ]; then
            new_tag="0.0.0"
        else
            # Split the latest tag into its components (assuming semantic versioning)
            IFS='.' read -r -a version_parts <<< "$latest_tag"
        fi

        # Get the commit message for the current commit
        COMMIT_MESSAGE=$(git log -1 --pretty=%B $COMMIT_SHA)

        echo $COMMIT_MESSAGE
        
  - name: 'docker'
    args: ["build", "-t", "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/ds-usecase-image:my-tag-b", "."]

  - name: "docker"
    args: ["push", "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/ds-usecase-image:my-tag-b"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["gcloud", "auth", "configure-docker", "europe-west2-docker.pkg.dev"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["gcloud", "container", "clusters", "get-credentials", "cluster-1", "--region=europe-west2", "--project=playpen-ff1b21"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["kubectl", "config", "current-context"]

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    script: |
      gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://europe-west2-docker.pkg.dev

  - name: "europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/playpen-base-image"
    args: ["helm", "upgrade", "--install", "ds-usecase-temp", "--set=image.repository=europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/ds-usecase-image", "--set=image.tag=my-tag-b", "oci://europe-west2-docker.pkg.dev/playpen-ff1b21/helm-artifact-repo/service-with-auth", "--version", "0.1.0"]
